language: csharp
mono: none
sudo: required
dotnet: 2.2
script:
    - dotnet restore **/*.csproj
    - dotnet build src/**/*.csproj
    - dotnet test tests/**/*.csproj --no-build
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1